"""Render boardroom simulation trace JSON into a human-readable Markdown report."""

from __future__ import annotations

import argparse
from pathlib import Path

from boardroom_sim.trace_report import load_trace_cases, render_report, select_cases


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Render boardroom trace JSON as a readable Markdown report.")
    parser.add_argument("--trace-json", type=Path, required=True, help="Path to trace JSON generated by an experiment run.")
    parser.add_argument("--output", type=Path, required=True, help="Path to the generated Markdown report.")
    parser.add_argument("--case-index", type=int, default=None, help="Optional zero-based case index to render.")
    parser.add_argument("--case-id", default=None, help="Optional case_id to render.")
    return parser.parse_args()


def main() -> None:
    """Load trace JSON and write the readable report."""
    args = parse_args()
    cases = load_trace_cases(args.trace_json)
    selected = select_cases(cases, case_index=args.case_index, case_id=args.case_id)
    report = render_report(selected)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"Wrote readable trace report to {args.output}.")


if __name__ == "__main__":
    main()
