"""Render boardroom simulation trace JSON into a human-readable narrative report."""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


ROLE_DESCRIPTIONS = {
    "Founder_CEO": "创始人兼 CEO，代表公司长期价值、控制权与融资需求。",
    "CTO": "技术负责人，代表工程资源、技术可行性与团队健康。",
    "Lead_VC_Director": "领投 VC 董事，代表定价权、条款保护和下行风险控制。",
    "Followon_VC_Director": "跟投 VC 董事，代表 pro-rata 权利、跟投纪律和对领投方的制衡。",
}


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description="Render boardroom trace JSON as a readable text report.")
    parser.add_argument("--trace-json", type=Path, required=True, help="Path to trace JSON generated by run_experiment.py.")
    parser.add_argument("--output", type=Path, required=True, help="Path to the generated text report.")
    parser.add_argument("--case-index", type=int, default=None, help="Optional zero-based case index to render.")
    parser.add_argument("--case-id", default=None, help="Optional case_id to render.")
    return parser.parse_args()


def main() -> None:
    """Load trace JSON and write the narrative report."""
    args = parse_args()
    cases = load_trace_cases(args.trace_json)
    selected = select_cases(cases, case_index=args.case_index, case_id=args.case_id)
    report = render_report(selected)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(f"Wrote readable trace report to {args.output}.")


def load_trace_cases(path: Path) -> List[Dict[str, Any]]:
    """Load a trace JSON file that contains either one case object or a case list."""
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        return [payload]
    raise ValueError(f"Expected a JSON object or list in {path}.")


def select_cases(
    cases: List[Dict[str, Any]],
    *,
    case_index: Optional[int],
    case_id: Optional[str],
) -> List[Dict[str, Any]]:
    """Select cases by index or case_id, defaulting to all cases."""
    if case_index is not None and case_id is not None:
        raise ValueError("Use either --case-index or --case-id, not both.")
    if case_index is not None:
        if case_index < 0 or case_index >= len(cases):
            raise IndexError(f"--case-index {case_index} is out of range for {len(cases)} cases.")
        return [cases[case_index]]
    if case_id is not None:
        selected = [case for case in cases if str(case.get("case_id", "")) == case_id]
        if not selected:
            raise ValueError(f"No case with case_id={case_id} found.")
        return selected
    return cases


def render_report(cases: List[Dict[str, Any]]) -> str:
    """Render all selected cases as one text report."""
    parts = ["董事会智能体模拟过程记录", ""]
    for index, case in enumerate(cases, start=1):
        parts.append(render_case(case, index=index, total=len(cases)))
        if index < len(cases):
            parts.append("\n" + "=" * 72 + "\n")
    return "\n".join(parts).rstrip() + "\n"


def render_case(case: Dict[str, Any], *, index: int, total: int) -> str:
    """Render one simulation case as readable prose."""
    trace = ensure_list(case.get("trace"))
    case_id = text(case.get("case_id"), "unknown_case")
    company = text(case.get("company_name"), "unknown_company")
    preliminary = first_event(trace, "preliminary")
    role_policy = first_event(trace, "role_policy")

    lines: List[str] = []
    title = f"案例 {index}/{total}：{company}（case_id: {case_id}）" if total > 1 else f"案例：{company}（case_id: {case_id}）"
    lines.extend([title, ""])

    lines.append("一、背景信息")
    if preliminary:
        lines.append(f"本次模拟的共同背景为：{text(preliminary.get('message'), '未记录背景摘要')}")
    else:
        lines.append("本次模拟没有在 trace 中记录单独的背景摘要。")
    lines.append(render_member_background(role_policy, case))
    lines.append("")

    lines.append("二、角色初始判断")
    private_events = [event for event in trace if event.get("stage") == "private_assessment"]
    if private_events:
        for event in private_events:
            actor = text(event.get("actor"), "unknown_actor")
            payload = ensure_dict(event.get("payload"))
            lines.append(f"{actor} 的初始立场是：{format_stance(payload)}")
            rationale = text(event.get("message"), "")
            if rationale:
                lines.append(f"该角色给出的主要理由是：{rationale}")
    else:
        lines.append("trace 中没有记录 private_assessment 阶段。")
    lines.append("")

    lines.append("三、开场陈述")
    opening_events = [event for event in trace if event.get("stage") == "opening_statement"]
    if opening_events:
        for event in opening_events:
            lines.append(f"{text(event.get('actor'), 'unknown_actor')}：{text(event.get('message'), '')}")
    else:
        lines.append("trace 中没有记录 opening_statement 阶段。")
    lines.append("")

    lines.append("四、辩论记录")
    lines.extend(render_bargaining(trace))
    lines.append("")

    lines.append("五、最终结果")
    lines.append(render_final_result(case))
    lines.append("")

    lines.append("六、模拟结果与真实结果相似度")
    lines.extend(render_similarity(case))
    return "\n".join(lines)


def render_member_background(role_policy_event: Optional[Dict[str, Any]], case: Dict[str, Any]) -> str:
    """Render role identities from role policy payload or final role decisions."""
    role_names: List[str] = []
    payload = ensure_dict(role_policy_event.get("payload")) if role_policy_event else {}
    if payload:
        role_names = [str(name) for name in payload.keys()]
    if not role_names:
        role_names = [str(name) for name in ensure_dict(case.get("role_decisions")).keys()]
    if not role_names:
        role_names = list(ROLE_DESCRIPTIONS.keys())

    descriptions = []
    for role in role_names:
        description = ROLE_DESCRIPTIONS.get(role, "董事会模拟成员。").rstrip("。")
        descriptions.append(f"{role}：{description}")
    return "参与本轮讨论的成员包括：" + "；".join(descriptions) + "。"


def render_bargaining(trace: List[Dict[str, Any]]) -> List[str]:
    """Render bargaining events grouped by round."""
    lines: List[str] = []
    rounds: Dict[str, List[Dict[str, Any]]] = {}
    proposals: Dict[str, Dict[str, Any]] = {}
    for event in trace:
        stage = text(event.get("stage"), "")
        if stage.startswith("bargaining_round_"):
            rounds.setdefault(stage, []).append(event)
        elif stage.startswith("proposal_after_round_"):
            proposals[stage.replace("proposal_after_", "bargaining_")] = event

    if not rounds:
        lines.append("本次模拟没有设置辩论轮，或 trace 中没有记录 bargaining_round 阶段。")
        return lines

    for stage in sorted(rounds, key=round_sort_key):
        round_no = stage.rsplit("_", 1)[-1]
        lines.append(f"第 {round_no} 轮辩论：")
        for event in rounds[stage]:
            actor = text(event.get("actor"), "unknown_actor")
            message = text(event.get("message"), "")
            payload = ensure_dict(event.get("payload"))
            updated = ensure_dict(payload.get("updated_decision") or payload.get("current_decision"))
            lines.append(f"{actor} 发言：{message}")
            if updated:
                lines.append(f"发言后，该角色的立场更新为：{format_stance(updated)}")
        proposal_event = proposals.get(stage)
        if proposal_event:
            proposal = ensure_dict(proposal_event.get("payload"))
            lines.append(f"本轮结束后的综合提案为：{format_proposal(proposal)}")
    return lines


def render_final_result(case: Dict[str, Any]) -> str:
    """Render final prediction in prose."""
    if "financing_initiation_decision" in case:
        return (
            f"最终聚合结果认为，公司融资意向为 {text(case.get('financing_initiation_decision'))}，"
            f"交易完成判断为 {text(case.get('financing_completion_view'))}。"
            f"模拟预测融资额为 {number(case.get('predicted_deal_size_usd_m'))} 百万美元，"
            f"交易类型为 {text(case.get('predicted_deal_type'))}，"
            f"估值方向判断为 {text(case.get('valuation_direction'))}，"
            f"CEO 更换判断为 {text(case.get('ceo_replacement_decision'))}。"
            f"共识分数为 {number(case.get('consensus_score'))}，"
            f"交易破裂风险为 {text(case.get('deal_break_risk'))}，"
            f"治理冲突风险为 {text(case.get('governance_conflict_risk'))}。"
        )
    return (
        f"最终聚合结果认为，融资决策为 {text(case.get('financing_decision'))}，"
        f"估值方向为 {text(case.get('valuation_direction'))}，"
        f"CEO 更换判断为 {text(case.get('ceo_replacement_decision'))}。"
        f"共识分数为 {number(case.get('consensus_score'))}，"
        f"交易破裂风险为 {text(case.get('deal_break_risk'))}，"
        f"治理冲突风险为 {text(case.get('governance_conflict_risk'))}。"
    )


def render_similarity(case: Dict[str, Any]) -> List[str]:
    """Render similarity between simulated predictions and labels."""
    labels = ensure_dict(case.get("labels"))
    if not labels:
        return ["该 trace 没有包含 labels 字段，因此无法计算模拟结果与真实结果的相似度。"]

    comparisons: List[Tuple[str, Optional[float], str]] = []
    comparisons.append(
        compare_exact(
            "融资意向",
            text(case.get("financing_initiation_decision"), ""),
            text(labels.get("true_financing_initiated_label"), ""),
        )
    )
    comparisons.append(
        compare_exact(
            "交易完成状态",
            text(case.get("financing_completion_view"), ""),
            map_completion_label(labels.get("real_deal_completed_label")),
        )
    )
    comparisons.append(
        compare_numeric(
            "融资额",
            to_float(case.get("predicted_deal_size_usd_m")),
            to_float(labels.get("real_deal_size_usd_m")),
            unit="百万美元",
        )
    )
    comparisons.append(compare_exact("交易类型", text(case.get("predicted_deal_type"), ""), text(labels.get("real_deal_type"), "")))
    comparisons.append(
        compare_exact(
            "估值方向",
            text(case.get("valuation_direction"), ""),
            text(labels.get("real_valuation_direction_label"), ""),
            skip_values={"", "unknown"},
        )
    )
    comparisons.append(
        compare_ceo(
            text(case.get("ceo_replacement_decision"), ""),
            text(labels.get("real_ceo_replacement_label"), ""),
        )
    )

    available = [(name, score, detail) for name, score, detail in comparisons if score is not None]
    if not available:
        return ["真实标签均缺失或不可比较，因此无法计算相似度。"]

    overall = sum(score for _, score, _ in available) / len(available)
    lines = [f"总体相似度为 {overall:.1%}，基于 {len(available)} 个可比较指标。"]
    for _, _, detail in available:
        lines.append(detail)
    skipped = [name for name, score, _ in comparisons if score is None]
    if skipped:
        lines.append("未纳入相似度计算的指标包括：" + "、".join(skipped) + "。")
    return lines


def format_stance(decision: Dict[str, Any]) -> str:
    """Format a role decision payload into one sentence."""
    if "financing_intent" in decision:
        return (
            f"融资意向 {text(decision.get('financing_intent'))}，"
            f"完成判断 {text(decision.get('completion_view'))}，"
            f"预计融资额 {number(decision.get('predicted_deal_size_usd_m'))} 百万美元，"
            f"交易类型 {text(decision.get('predicted_deal_type'))}，"
            f"估值方向 {text(decision.get('valuation_direction'))}，"
            f"CEO 更换观点 {text(decision.get('ceo_replacement_view'))}，"
            f"满意度 {number(decision.get('satisfaction_score'))}。"
        )
    return (
        f"融资投票 {text(decision.get('financing_vote'))}，"
        f"估值方向 {text(decision.get('valuation_direction'))}，"
        f"CEO 更换观点 {text(decision.get('ceo_replacement_view'))}，"
        f"满意度 {number(decision.get('satisfaction_score'))}。"
    )


def format_proposal(proposal: Dict[str, Any]) -> str:
    """Format an aggregated proposal payload."""
    if not proposal:
        return "未记录具体提案。"
    if "recommended_deal_size_usd_m" in proposal:
        return (
            f"建议融资额 {number(proposal.get('recommended_deal_size_usd_m'))} 百万美元，"
            f"交易类型 {text(proposal.get('recommended_deal_type'))}，"
            f"估值方向 {text(proposal.get('valuation_direction'))}，"
            f"预计稀释 {number(proposal.get('estimated_dilution_pct'))}%，"
            f"投资人保护强度 {text(proposal.get('investor_protection_level'))}。"
        )
    return ", ".join(f"{key}={value}" for key, value in proposal.items())


def compare_exact(
    name: str,
    predicted: str,
    actual: str,
    *,
    skip_values: Optional[Iterable[str]] = None,
) -> Tuple[str, Optional[float], str]:
    """Compare categorical predictions."""
    skips = set(skip_values or {"", "unknown"})
    if predicted in skips or actual in skips:
        return name, None, f"{name}缺少可比较标签。"
    score = 1.0 if predicted == actual else 0.0
    return name, score, f"{name}：模拟为 {predicted}，真实为 {actual}，相似度 {score:.0%}。"


def compare_ceo(predicted: str, actual: str) -> Tuple[str, Optional[float], str]:
    """Compare CEO replacement labels, treating monitor as partial pressure."""
    if not predicted or not actual or actual == "unknown":
        return "CEO 更换", None, "CEO 更换缺少可比较标签。"
    if predicted == actual:
        score = 1.0
    elif predicted == "monitor" and actual in {"keep", "replace"}:
        score = 0.5
    else:
        score = 0.0
    return "CEO 更换", score, f"CEO 更换：模拟为 {predicted}，真实为 {actual}，相似度 {score:.0%}。"


def compare_numeric(name: str, predicted: Optional[float], actual: Optional[float], *, unit: str) -> Tuple[str, Optional[float], str]:
    """Compare numeric prediction with relative-error similarity."""
    if predicted is None or actual is None or actual <= 0:
        return name, None, f"{name}缺少可比较数值。"
    relative_error = abs(predicted - actual) / max(abs(actual), 1.0)
    score = max(0.0, 1.0 - relative_error)
    return (
        name,
        score,
        f"{name}：模拟为 {predicted:.3f} {unit}，真实为 {actual:.3f} {unit}，"
        f"相对误差 {relative_error:.1%}，相似度 {score:.1%}。",
    )


def map_completion_label(label: Any) -> str:
    """Map raw deal status into the simulation completion-view label space."""
    raw = text(label, "").strip().lower()
    if raw in {"completed", "closed", "done"}:
        return "likely_complete"
    if raw in {"cancelled", "canceled", "failed", "terminated", "withdrawn"}:
        return "unlikely_complete"
    if raw:
        return "uncertain"
    return ""


def first_event(trace: List[Dict[str, Any]], stage: str) -> Optional[Dict[str, Any]]:
    """Return the first trace event with a given stage."""
    for event in trace:
        if event.get("stage") == stage:
            return event
    return None


def ensure_dict(value: Any) -> Dict[str, Any]:
    """Return value if it is a dict, else an empty dict."""
    return value if isinstance(value, dict) else {}


def ensure_list(value: Any) -> List[Dict[str, Any]]:
    """Return value if it is a list of dict-like events, else an empty list."""
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def text(value: Any, default: str = "unknown") -> str:
    """Convert a value into readable text."""
    if value is None:
        return default
    value_text = str(value).strip()
    return value_text if value_text else default


def number(value: Any) -> str:
    """Format numeric values without noisy trailing zeros."""
    numeric = to_float(value)
    if numeric is None:
        return "未知"
    return f"{numeric:.6g}"


def to_float(value: Any) -> Optional[float]:
    """Convert value to float if possible."""
    try:
        if value is None or value == "":
            return None
        number_value = float(value)
        return number_value if math.isfinite(number_value) else None
    except (TypeError, ValueError):
        return None


def round_sort_key(stage: str) -> int:
    """Sort bargaining round stage names by trailing integer."""
    try:
        return int(stage.rsplit("_", 1)[-1])
    except ValueError:
        return 0


if __name__ == "__main__":
    main()
