"""Human-readable Markdown rendering for boardroom simulation traces."""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

from boardroom_sim.models import SimulationResult


ROLE_LABELS = {
    "Founder_CEO": "创始人兼 CEO",
    "CTO": "技术负责人 CTO",
    "Lead_VC_Director": "领投 VC 董事",
    "Followon_VC_Director": "跟投 VC 董事",
}

DECISION_FIELD_LABELS = {
    "financing_intent": "融资意图",
    "completion_view": "交易完成判断",
    "predicted_deal_size_usd_m": "预测融资额（百万美元）",
    "predicted_post_money_valuation_usd_m": "预测投后估值（百万美元）",
    "predicted_investor_ownership_pct": "预测投资人持股（%）",
    "predicted_deal_type": "预测交易类型",
    "valuation_direction": "估值方向",
    "satisfaction_score": "角色满意度",
}

PROPOSAL_FIELD_LABELS = {
    "recommended_deal_size_usd_m": "建议融资额（百万美元）",
    "recommended_post_money_valuation_usd_m": "建议投后估值（百万美元）",
    "recommended_investor_ownership_pct": "建议投资人持股（%）",
    "recommended_deal_type": "建议交易类型",
    "valuation_direction": "估值方向",
    "estimated_dilution_pct": "估计稀释比例（%）",
    "investor_protection_level": "投资人保护强度",
    "tech_budget_protected": "是否保护技术预算",
}

FINAL_FIELD_LABELS = {
    "financing_initiation_decision": "最终融资意图",
    "financing_completion_view": "最终完成判断",
    "predicted_deal_size_usd_m": "最终预测融资额（百万美元）",
    "predicted_post_money_valuation_usd_m": "最终预测投后估值（百万美元）",
    "predicted_investor_ownership_pct": "最终预测投资人持股（%）",
    "predicted_deal_type": "最终预测交易类型",
    "valuation_direction": "最终估值方向",
    "consensus_score": "共识分数",
    "deal_break_risk": "交易破裂风险",
}

ARTIFACT_LABELS = {
    "boardroom_act": "会议行为",
    "direct_response_to": "直接回应对象",
    "questions_raised": "提出的问题",
    "evidence_anchors": "证据锚点",
    "alternative_options": "替代方案",
    "role_commitment": "角色承诺",
    "prediction_update_reason": "预测更新理由",
}


def write_readable_trace_report(path: Path, results: Iterable[SimulationResult]) -> None:
    """Write simulation results as a readable Markdown trace report."""
    path.parent.mkdir(parents=True, exist_ok=True)
    cases = [result.to_dict(include_trace=True) for result in results]
    path.write_text(render_report(cases), encoding="utf-8")


def load_trace_cases(path: Path) -> List[Dict[str, Any]]:
    """Load trace JSON generated by run_experiment.py or run_batch_experiments.py."""
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]
    if isinstance(payload, dict):
        return [payload]
    raise ValueError(f"Expected a JSON object or list in {path}.")


def select_cases(
    cases: List[Dict[str, Any]],
    *,
    case_index: Optional[int] = None,
    case_id: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """Select cases by index or case_id; default to all cases."""
    if case_index is not None and case_id is not None:
        raise ValueError("Use either case_index or case_id, not both.")
    if case_index is not None:
        if case_index < 0 or case_index >= len(cases):
            raise IndexError(f"case_index {case_index} is out of range for {len(cases)} cases.")
        return [cases[case_index]]
    if case_id is not None:
        selected = [case for case in cases if str(case.get("case_id", "")) == case_id]
        if not selected:
            raise ValueError(f"No case with case_id={case_id} found.")
        return selected
    return cases


def render_report(cases: List[Dict[str, Any]]) -> str:
    """Render selected simulation cases as a Markdown report."""
    parts = [
        "# 董事会模拟过程记录",
        "",
        f"- 案例数：{len(cases)}",
        "- 说明：本报告根据结构化 trace 自动生成，用于检查角色发言、观点变化、会议流程和最终聚合是否符合真实董事会讨论直觉。",
        "",
    ]
    for index, case in enumerate(cases, start=1):
        parts.append(render_case(case, index=index, total=len(cases)))
    return "\n".join(parts).rstrip() + "\n"


def render_case(case: Dict[str, Any], *, index: int, total: int) -> str:
    """Render one case, including process settings and all discussion rounds."""
    trace = ensure_list(case.get("trace"))
    case_id = text(case.get("case_id"), "unknown_case")
    company = text(case.get("company_name"), "unknown_company")
    title = f"## 案例 {index}/{total}：{company}（case_id: {case_id}）"

    initial_decisions = decisions_from_initial_assessment(trace)
    final_proposal = ensure_dict(case.get("proposal"))

    sections = [
        title,
        render_case_background(case, trace),
        render_process_settings(trace),
        render_initial_assessments(trace, initial_decisions),
        render_opening_statements(trace),
        render_discussion_rounds(trace, initial_decisions),
        render_final_outputs(case, final_proposal),
        render_labels(case),
    ]
    return "\n\n".join(section for section in sections if section)


def render_case_background(case: Dict[str, Any], trace: List[Dict[str, Any]]) -> str:
    """Render shared background visible in the trace."""
    preliminary = first_event(trace, "preliminary")
    lines = ["### 1. 案例背景"]
    if preliminary:
        lines.append(text(preliminary.get("message"), "trace 未记录背景摘要。"))
    else:
        lines.append("trace 未记录背景摘要。")
    labels = ensure_dict(case.get("labels"))
    if labels:
        lines.append("")
        lines.append("真实标签存在，但不会进入角色可见信息；它们只用于事后评估。")
    return "\n".join(lines)


def render_process_settings(trace: List[Dict[str, Any]]) -> str:
    """Render board process, archetype, L5 culture, and weights."""
    event = first_event(trace, "board_process")
    if not event:
        return "### 2. 董事会流程设置\ntrace 未记录 board_process。"

    payload = ensure_dict(event.get("payload"))
    process = ensure_dict(payload.get("process"))
    base_weights = ensure_dict(payload.get("base_role_weights"))
    effective_weights = ensure_dict(payload.get("effective_role_weights"))
    culture = ensure_dict(process.get("culture"))

    lines = [
        "### 2. 董事会流程设置",
        markdown_table(
            ["变量", "值"],
            [
                ["board archetype", process.get("archetype")],
                ["archetype label", process.get("archetype_label")],
                ["discussion protocol", process.get("protocol")],
                ["dominance pattern", process.get("dominance_pattern")],
                ["memory scope", process.get("memory_scope")],
                ["memory window", process.get("memory_window")],
                ["challenge required", process.get("challenge_required")],
                ["culture layer", process.get("culture_layer")],
            ],
        ),
    ]
    if culture:
        lines.extend(["", "**L5 文化层参数**", markdown_table(["维度", "数值"], culture.items())])
    if base_weights or effective_weights:
        role_names = sorted(set(base_weights) | set(effective_weights))
        lines.extend(
            [
                "",
                "**角色权重**",
                markdown_table(
                    ["角色", "基础权重", "流程调整后权重"],
                    [[role_label(role), base_weights.get(role), effective_weights.get(role)] for role in role_names],
                ),
            ]
        )
    return "\n".join(lines)


def render_initial_assessments(
    trace: List[Dict[str, Any]],
    initial_decisions: Dict[str, Dict[str, Any]],
) -> str:
    """Render each role's private initial prediction."""
    events = [event for event in trace if event.get("stage") == "private_assessment"]
    lines = ["### 3. 角色初始判断"]
    if not events:
        lines.append("trace 未记录 private_assessment。")
        return "\n".join(lines)

    for event in events:
        actor = text(event.get("actor"), "unknown_actor")
        decision = ensure_dict(event.get("payload")) or initial_decisions.get(actor, {})
        lines.append(f"#### {role_label(actor)}")
        lines.append(f"- 初始理由：{text(event.get('message'), '未记录。')}")
        lines.append(decision_table(decision))
    return "\n".join(lines)


def render_opening_statements(trace: List[Dict[str, Any]]) -> str:
    """Render role opening statements."""
    events = [event for event in trace if event.get("stage") == "opening_statement"]
    lines = ["### 4. 开场陈述"]
    if not events:
        lines.append("trace 未记录 opening_statement。")
        return "\n".join(lines)
    for event in events:
        lines.append(f"- **{role_label(event.get('actor'))}**：{text(event.get('message'), '')}")
    return "\n".join(lines)


def render_discussion_rounds(
    trace: List[Dict[str, Any]],
    initial_decisions: Dict[str, Dict[str, Any]],
) -> str:
    """Render all bargaining rounds, including speech and prediction changes."""
    round_numbers = bargaining_round_numbers(trace)
    lines = ["### 5. 逐轮讨论记录"]
    if not round_numbers:
        lines.append("trace 未记录 bargaining_round。")
        return "\n".join(lines)

    current_decisions = {role: dict(decision) for role, decision in initial_decisions.items()}
    for round_number in round_numbers:
        lines.append(f"#### 第 {round_number} 轮")
        process_event = first_event(trace, f"process_round_{round_number}")
        if process_event:
            process_payload = ensure_dict(process_event.get("payload"))
            speakers = ensure_list_or_values(process_payload.get("speaking_order"))
            lines.append(f"- 发言顺序：{', '.join(role_label(role) for role in speakers) if speakers else '未记录'}")

        round_events = [event for event in trace if event.get("stage") == f"bargaining_round_{round_number}"]
        if round_events:
            context = ensure_dict(ensure_dict(round_events[0].get("payload")).get("process_context"))
            lines.append(render_round_context(context))

        for event in round_events:
            if text(event.get("actor"), "") == "system":
                lines.append(f"- 系统记录：{text(event.get('message'), '')}")
                continue
            actor = text(event.get("actor"), "unknown_actor")
            payload = ensure_dict(event.get("payload"))
            after = ensure_dict(payload.get("updated_decision"))
            before = current_decisions.get(actor, {})
            changed = ensure_list_or_values(payload.get("changed_fields"))
            artifacts = ensure_dict(payload.get("meeting_artifacts"))

            lines.append(f"##### {role_label(actor)} 发言")
            lines.append(blockquote(text(event.get("message"), "")))
            lines.append(render_meeting_artifacts(artifacts))
            lines.append(render_decision_changes(before, after, changed))
            if after:
                current_decisions[actor] = after

        proposal_event = first_event(trace, f"proposal_after_round_{round_number}")
        if proposal_event:
            proposal = ensure_dict(proposal_event.get("payload"))
            lines.append("**本轮结束后的综合提案**")
            lines.append(proposal_table(proposal))
        process_decision = first_event(trace, f"process_decision_after_round_{round_number}")
        if process_decision:
            lines.append(render_continuation_decision(ensure_dict(process_decision.get("payload"))))
    return "\n".join(lines)


def render_round_context(context: Dict[str, Any]) -> str:
    """Render process context for a discussion round."""
    if not context:
        return "- 本轮过程上下文：未记录。"
    phase = ensure_dict(context.get("meeting_phase"))
    lines = [
        "- 本轮会议阶段："
        + text(phase.get("phase"), "unknown")
        + f"（目的：{text(phase.get('purpose'), '未记录')}）",
        f"- 本轮贡献要求：{text(phase.get('expected_contribution'), '未记录')}",
        f"- 过程指令：{text(context.get('process_instruction'), '未记录')}",
        f"- 挑战指令：{text(context.get('challenge_instruction'), '未记录')}",
    ]
    l5_policy = ensure_dict(context.get("l5_culture"))
    controls = ensure_dict(l5_policy.get("behavior_controls"))
    if controls:
        lines.append("- L5 行为控制：" + inline_mapping(controls))
    return "\n".join(lines)


def render_meeting_artifacts(artifacts: Dict[str, Any]) -> str:
    """Render structured boardroom behavior fields returned by the LLM."""
    if not artifacts:
        return "- 会议行为记录：未记录。"
    rows = []
    for key, label in ARTIFACT_LABELS.items():
        value = artifacts.get(key)
        if is_empty(value):
            continue
        rows.append([label, render_value(value)])
    if not rows:
        return "- 会议行为记录：未记录有效字段。"
    return "**会议行为记录**\n" + markdown_table(["字段", "内容"], rows)


def render_decision_changes(
    before: Dict[str, Any],
    after: Dict[str, Any],
    changed_fields: Iterable[Any],
) -> str:
    """Render how a role's prediction changed after one speech."""
    changed = [str(field) for field in changed_fields if str(field)]
    if not after:
        return "- 观点变化：未记录更新后的结构化判断。"
    if not changed:
        return "- 观点变化：结构化判断未发生字段变化。"
    rows = []
    for field in changed:
        rows.append(
            [
                DECISION_FIELD_LABELS.get(field, field),
                render_value(before.get(field, "未记录")),
                render_value(after.get(field, "未记录")),
            ]
        )
    return "**观点变化**\n" + markdown_table(["字段", "发言前", "发言后"], rows)


def render_final_outputs(case: Dict[str, Any], proposal: Dict[str, Any]) -> str:
    """Render final aggregated predictions and proposal."""
    rows = [[label, render_value(case.get(field))] for field, label in FINAL_FIELD_LABELS.items()]
    lines = ["### 6. 最终聚合结果", markdown_table(["字段", "值"], rows)]
    if proposal:
        lines.extend(["", "**最终 term sheet / 综合提案**", proposal_table(proposal)])
    return "\n".join(lines)


def render_continuation_decision(payload: Dict[str, Any]) -> str:
    """Render the process controller's continue-or-close decision."""
    if not payload:
        return "**流程判断**\n\n未记录。"
    action = "继续讨论" if payload.get("continue_discussion") else "结束讨论，进入最终聚合"
    rows = [
        ["流程动作", action],
        ["当前共识分数", payload.get("consensus_score")],
        ["本轮改变结构化预测的角色数", payload.get("changed_role_count")],
        ["连续无结构化变化轮数", payload.get("no_change_round_streak")],
        ["本轮开放问题", payload.get("open_questions_this_round")],
        ["本轮替代方案", payload.get("alternative_options_this_round")],
        ["判断理由", payload.get("reasons")],
    ]
    return "**流程判断**\n" + markdown_table(["字段", "值"], rows)


def render_labels(case: Dict[str, Any]) -> str:
    """Render ground-truth labels for post-run inspection."""
    labels = ensure_dict(case.get("labels"))
    if not labels:
        return "### 7. 真实标签\n本案例 trace 未包含真实标签。"
    rows = [[key, render_value(value)] for key, value in sorted(labels.items())]
    return "### 7. 真实标签（仅用于事后对照）\n" + markdown_table(["标签字段", "真实值"], rows)


def decisions_from_initial_assessment(trace: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    """Return role decisions recorded at private_assessment stage."""
    decisions: Dict[str, Dict[str, Any]] = {}
    for event in trace:
        if event.get("stage") != "private_assessment":
            continue
        actor = text(event.get("actor"), "")
        payload = ensure_dict(event.get("payload"))
        if actor and payload:
            decisions[actor] = payload
    return decisions


def bargaining_round_numbers(trace: List[Dict[str, Any]]) -> List[int]:
    """Extract bargaining round numbers from trace stage names."""
    numbers = set()
    for event in trace:
        stage = text(event.get("stage"), "")
        if not stage.startswith("bargaining_round_"):
            continue
        try:
            numbers.add(int(stage.rsplit("_", 1)[-1]))
        except ValueError:
            continue
    return sorted(numbers)


def decision_table(decision: Dict[str, Any]) -> str:
    """Render a compact role-decision table."""
    rows = []
    for field, label in DECISION_FIELD_LABELS.items():
        if field in decision:
            rows.append([label, render_value(decision.get(field))])
    rationale = decision.get("rationale")
    if rationale:
        rows.append(["理由列表", render_value(rationale)])
    return markdown_table(["字段", "值"], rows) if rows else "未记录结构化判断。"


def proposal_table(proposal: Dict[str, Any]) -> str:
    """Render a compact proposal table."""
    rows = []
    for field, label in PROPOSAL_FIELD_LABELS.items():
        if field in proposal:
            rows.append([label, render_value(proposal.get(field))])
    if not rows:
        rows = [[key, render_value(value)] for key, value in proposal.items()]
    return markdown_table(["字段", "值"], rows)


def first_event(trace: List[Dict[str, Any]], stage: str) -> Optional[Dict[str, Any]]:
    """Return the first trace event with a matching stage."""
    for event in trace:
        if event.get("stage") == stage:
            return event
    return None


def markdown_table(headers: Iterable[Any], rows: Iterable[Iterable[Any]]) -> str:
    """Render a simple Markdown table."""
    header_list = [table_cell(header) for header in headers]
    body_rows = [[table_cell(value) for value in row] for row in rows]
    lines = [
        "| " + " | ".join(header_list) + " |",
        "| " + " | ".join("---" for _ in header_list) + " |",
    ]
    for row in body_rows:
        padded = row + [""] * (len(header_list) - len(row))
        lines.append("| " + " | ".join(padded[: len(header_list)]) + " |")
    return "\n".join(lines)


def blockquote(value: str) -> str:
    """Render text as Markdown blockquote."""
    if not value:
        return "> 未记录发言。"
    return "\n".join(f"> {line}" if line else ">" for line in value.splitlines())


def inline_mapping(value: Dict[str, Any]) -> str:
    """Render a small mapping in one readable line."""
    return "；".join(f"{key}={render_value(item)}" for key, item in value.items())


def role_label(role: Any) -> str:
    """Return a readable role label while preserving the raw role name."""
    raw = text(role, "unknown_actor")
    label = ROLE_LABELS.get(raw)
    return f"{label}（{raw}）" if label else raw


def render_value(value: Any) -> str:
    """Render values for Markdown tables without losing structured content."""
    if value is None:
        return "未记录"
    if isinstance(value, float):
        if not math.isfinite(value):
            return "未记录"
        return f"{value:.6g}"
    if isinstance(value, (dict, list, tuple)):
        return json.dumps(value, ensure_ascii=False, separators=(",", ": "))
    if isinstance(value, bool):
        return "是" if value else "否"
    text_value = str(value).strip()
    return text_value if text_value else "未记录"


def table_cell(value: Any) -> str:
    """Escape Markdown table cell content."""
    return render_value(value).replace("\n", " ").replace("|", "\\|")


def ensure_dict(value: Any) -> Dict[str, Any]:
    """Return value as dict if possible, else an empty dict."""
    return value if isinstance(value, dict) else {}


def ensure_list(value: Any) -> List[Dict[str, Any]]:
    """Return a list of dict events."""
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def ensure_list_or_values(value: Any) -> List[Any]:
    """Return a list for list-like trace values."""
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    if value is None:
        return []
    return [value]


def text(value: Any, default: str = "unknown") -> str:
    """Convert a value to readable text."""
    if value is None:
        return default
    value_text = str(value).strip()
    return value_text if value_text else default


def is_empty(value: Any) -> bool:
    """Return whether a trace field should be treated as empty."""
    return value is None or value == "" or value == [] or value == {}
